# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 610)
        MainWindow.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_school = QtWidgets.QLabel(self.centralwidget)
        self.label_school.setGeometry(QtCore.QRect(92, 0, 611, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        self.label_school.setFont(font)
        self.label_school.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_school.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_school.setAlignment(QtCore.Qt.AlignCenter)
        self.label_school.setObjectName("label_school")
        self.label_logo_khoa = QtWidgets.QLabel(self.centralwidget)
        self.label_logo_khoa.setGeometry(QtCore.QRect(699, 0, 101, 91))
        self.label_logo_khoa.setStyleSheet("border-image: url(:/logo/logo_khoa.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_logo_khoa.setText("")
        self.label_logo_khoa.setObjectName("label_logo_khoa")
        self.label_logo_truong = QtWidgets.QLabel(self.centralwidget)
        self.label_logo_truong.setGeometry(QtCore.QRect(0, 0, 91, 91))
        self.label_logo_truong.setStyleSheet("border-image: url(:/logo/logo_truong.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_logo_truong.setText("")
        self.label_logo_truong.setObjectName("label_logo_truong")
        self.label_monhoc = QtWidgets.QLabel(self.centralwidget)
        self.label_monhoc.setGeometry(QtCore.QRect(110, 153, 571, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.label_monhoc.setFont(font)
        self.label_monhoc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_monhoc.setStyleSheet("")
        self.label_monhoc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_monhoc.setObjectName("label_monhoc")
        self.label_detai = QtWidgets.QLabel(self.centralwidget)
        self.label_detai.setGeometry(QtCore.QRect(78, 220, 641, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        self.label_detai.setFont(font)
        self.label_detai.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_detai.setStyleSheet("")
        self.label_detai.setAlignment(QtCore.Qt.AlignCenter)
        self.label_detai.setObjectName("label_detai")
        self.label_ten = QtWidgets.QLabel(self.centralwidget)
        self.label_ten.setGeometry(QtCore.QRect(520, 380, 261, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        self.label_ten.setFont(font)
        self.label_ten.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ten.setStyleSheet("")
        self.label_ten.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ten.setObjectName("label_ten")
        self.label_thoigian = QtWidgets.QLabel(self.centralwidget)
        self.label_thoigian.setGeometry(QtCore.QRect(210, 530, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label_thoigian.setFont(font)
        self.label_thoigian.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_thoigian.setStyleSheet("")
        self.label_thoigian.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thoigian.setObjectName("label_thoigian")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(350, 330, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.start_btn.setFont(font)
        self.start_btn.setStyleSheet("background-color: rgb(170, 170, 170);")
        self.start_btn.setObjectName("start_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_school.setText(_translate("MainWindow", "<html><head/><body><p>Trường Đại học Sư phạm Kỹ thuật </p><p>Thành phố Hồ Chí Minh</p></body></html>"))
        self.label_monhoc.setText(_translate("MainWindow", "<html><head/><body><p>ĐỒ ÁN ĐIỀU KHIỂN LẬP TRÌNH</p></body></html>"))
        self.label_detai.setText(_translate("MainWindow", "<html><head/><body><p>Thiết kế và điều khiển cánh tay robot phân loại và xếp hàng</p><p>ứng dụng xử lý ảnh</p></body></html>"))
        self.label_ten.setText(_translate("MainWindow", "<html><head/><body><p>GVHD: TS. Trần Vi Đô</p><p>SVTH: </p><p>Phạm Hữu Đạt - 21151212</p><p>Phạm Khải Nguyên - 21151293</p></body></html>"))
        self.label_thoigian.setText(_translate("MainWindow", "<html><head/><body><p>Tp. Hồ Chí Minh, ngày 23 tháng 12 năm 2024</p></body></html>"))
        self.start_btn.setText(_translate("MainWindow", "START"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
